//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.27 at 07:48:18 PM GMT 
//


package org.cara.webcarasearch.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cara.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cara.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTitleListStringWithRatingYear }
     * 
     */
    public GetTitleListStringWithRatingYear createGetTitleListStringWithRatingYear() {
        return new GetTitleListStringWithRatingYear();
    }

    /**
     * Create an instance of {@link GetTitleListStringFullWithPagination }
     * 
     */
    public GetTitleListStringFullWithPagination createGetTitleListStringFullWithPagination() {
        return new GetTitleListStringFullWithPagination();
    }

    /**
     * Create an instance of {@link GetTitleListStringFullWithPaginationMobile }
     * 
     */
    public GetTitleListStringFullWithPaginationMobile createGetTitleListStringFullWithPaginationMobile() {
        return new GetTitleListStringFullWithPaginationMobile();
    }

    /**
     * Create an instance of {@link GetTitleListStringFullWithPaginationMobileResponse }
     * 
     */
    public GetTitleListStringFullWithPaginationMobileResponse createGetTitleListStringFullWithPaginationMobileResponse() {
        return new GetTitleListStringFullWithPaginationMobileResponse();
    }

    /**
     * Create an instance of {@link GetTitleListByYearRatingForExport }
     * 
     */
    public GetTitleListByYearRatingForExport createGetTitleListByYearRatingForExport() {
        return new GetTitleListByYearRatingForExport();
    }

    /**
     * Create an instance of {@link GetTitleListStringFullWithPaginationResponse }
     * 
     */
    public GetTitleListStringFullWithPaginationResponse createGetTitleListStringFullWithPaginationResponse() {
        return new GetTitleListStringFullWithPaginationResponse();
    }

    /**
     * Create an instance of {@link GetTitleListStringFullForExport }
     * 
     */
    public GetTitleListStringFullForExport createGetTitleListStringFullForExport() {
        return new GetTitleListStringFullForExport();
    }

    /**
     * Create an instance of {@link GetTitleListByYearRatingFullWithPaginationResponse }
     * 
     */
    public GetTitleListByYearRatingFullWithPaginationResponse createGetTitleListByYearRatingFullWithPaginationResponse() {
        return new GetTitleListByYearRatingFullWithPaginationResponse();
    }

    /**
     * Create an instance of {@link GetTitleListStringFullForExportResponse }
     * 
     */
    public GetTitleListStringFullForExportResponse createGetTitleListStringFullForExportResponse() {
        return new GetTitleListStringFullForExportResponse();
    }

    /**
     * Create an instance of {@link GetTitleListStringWithNoRatingResponse }
     * 
     */
    public GetTitleListStringWithNoRatingResponse createGetTitleListStringWithNoRatingResponse() {
        return new GetTitleListStringWithNoRatingResponse();
    }

    /**
     * Create an instance of {@link GetTitleListStringWithPagination }
     * 
     */
    public GetTitleListStringWithPagination createGetTitleListStringWithPagination() {
        return new GetTitleListStringWithPagination();
    }

    /**
     * Create an instance of {@link GetTitleListStringWithRatingYearResponse }
     * 
     */
    public GetTitleListStringWithRatingYearResponse createGetTitleListStringWithRatingYearResponse() {
        return new GetTitleListStringWithRatingYearResponse();
    }

    /**
     * Create an instance of {@link GetExportWithTitleResponse }
     * 
     */
    public GetExportWithTitleResponse createGetExportWithTitleResponse() {
        return new GetExportWithTitleResponse();
    }

    /**
     * Create an instance of {@link GetTitleListStringWithNoRating }
     * 
     */
    public GetTitleListStringWithNoRating createGetTitleListStringWithNoRating() {
        return new GetTitleListStringWithNoRating();
    }

    /**
     * Create an instance of {@link GetTitleListByYearRatingWithPaginationResponse }
     * 
     */
    public GetTitleListByYearRatingWithPaginationResponse createGetTitleListByYearRatingWithPaginationResponse() {
        return new GetTitleListByYearRatingWithPaginationResponse();
    }

    /**
     * Create an instance of {@link GetTitleListByYearRatingWithPagination }
     * 
     */
    public GetTitleListByYearRatingWithPagination createGetTitleListByYearRatingWithPagination() {
        return new GetTitleListByYearRatingWithPagination();
    }

    /**
     * Create an instance of {@link GetExportWithTitleYear }
     * 
     */
    public GetExportWithTitleYear createGetExportWithTitleYear() {
        return new GetExportWithTitleYear();
    }

    /**
     * Create an instance of {@link GetTitleListStringWithPaginationResponse }
     * 
     */
    public GetTitleListStringWithPaginationResponse createGetTitleListStringWithPaginationResponse() {
        return new GetTitleListStringWithPaginationResponse();
    }

    /**
     * Create an instance of {@link GetExportWithTitle }
     * 
     */
    public GetExportWithTitle createGetExportWithTitle() {
        return new GetExportWithTitle();
    }

    /**
     * Create an instance of {@link GetTitleListByYearRatingFullWithPagination }
     * 
     */
    public GetTitleListByYearRatingFullWithPagination createGetTitleListByYearRatingFullWithPagination() {
        return new GetTitleListByYearRatingFullWithPagination();
    }

    /**
     * Create an instance of {@link GetExportWithTitleYearResponse }
     * 
     */
    public GetExportWithTitleYearResponse createGetExportWithTitleYearResponse() {
        return new GetExportWithTitleYearResponse();
    }

    /**
     * Create an instance of {@link GetTitleListByYearRatingForExportResponse }
     * 
     */
    public GetTitleListByYearRatingForExportResponse createGetTitleListByYearRatingForExportResponse() {
        return new GetTitleListByYearRatingForExportResponse();
    }

}
